import type { Product, Category } from "./types";

export const COMPANY = {
  name: "Мир Ремонта",
  city: "Семей",
  tagline: "Стройматериалы со склада. Доставка за 1 час.",
  phone: "+7 701 800 20 23",
  phoneHref: "tel:+77018002023",
  whatsappNumber: "77018002023",
  whatsapp: "https://wa.me/77018002023",
  email: "Mirremonta16@yandex.ru",
  address: "Абайская обл., г. Семей, ул. Чайковского 71А",
  hours: "Пн–Вс, 09:00–18:00",
  instagram: "https://instagram.com/mir_remonta_semey1",
  instagramHandle: "@mir_remonta_semey1",
  legalName: "ТОО «Атмосфера Уюта»",
  iik: "KZ128562203130326340",
  bank: "АО «Банк Центр Кредит»",
  bik: "KCBKZKX",
} as const;

export const CATEGORIES: Category[] = [
  {
    id: "metal",
    title: "Металлопрокат",
    subtitle: "Трубы, арматура, уголок",
    image: "/images/cat-metal.jpg",
  },
  {
    id: "smes",
    title: "Сухие смеси",
    subtitle: "Цемент, штукатурки, клей",
    image: "/images/cat-smes.jpg",
  },
  {
    id: "wood",
    title: "Плитные материалы",
    subtitle: "Фанера, ОСБ, гипсокартон",
    image: "/images/cat-wood.jpg",
  },
  {
    id: "profnastil",
    title: "Профнастил",
    subtitle: "Кровля и забор",
    image: "/images/cat-profnastil.jpg",
  },
  {
    id: "doors",
    title: "Двери",
    subtitle: "Деревянные и металлические",
    image: "/images/cat-doors.jpg",
  },
  {
    id: "floor",
    title: "Напольные покрытия",
    subtitle: "Ламинат, линолеум, погонаж",
    image: "/images/cat-floor.jpg",
  },
];

export const PRODUCTS: Product[] = [
  // METAL
  {
    slug: "truba-prof-20x20",
    title: "Труба профильная 20×20×1,5",
    brand: "Арселор",
    category: "metal",
    subcategory: "Профильные трубы",
    image: "/images/cat-metal.jpg",
    price: 920,
    unit: "м",
    inStock: 480,
    badge: "Хит",
    description:
      "Стальная профильная труба 20×20×1,5 мм. Сталь 09Г2С. Длина хлыста 6 м. Подходит для каркасов, ограждений, мебели.",
    specs: {
      Размер: "20×20 мм",
      Толщина: "1,5 мм",
      Длина: "6 м",
      Марка: "09Г2С",
    },
  },
  {
    slug: "truba-prof-40x40",
    title: "Труба профильная 40×40×2,0",
    brand: "Арселор",
    category: "metal",
    subcategory: "Профильные трубы",
    image: "/images/cat-metal.jpg",
    price: 1840,
    unit: "м",
    inStock: 320,
    description:
      "Стальная профильная труба 40×40×2,0 мм. Для несущих конструкций, навесов, ворот.",
    specs: { Размер: "40×40 мм", Толщина: "2,0 мм", Длина: "6 м" },
  },
  {
    slug: "armatura-a3-12",
    title: "Арматура А3 ⌀12 мм",
    brand: "ЕвразМеталл",
    category: "metal",
    subcategory: "Арматура",
    image: "/images/cat-metal.jpg",
    price: 380,
    unit: "м",
    inStock: 1200,
    description:
      "Рифлёная арматура класса А-III, диаметр 12 мм. Для армирования фундамента, колонн, перекрытий.",
    specs: { Диаметр: "12 мм", Класс: "А-III (А400)", Длина: "11,7 м" },
  },
  {
    slug: "armatura-a3-14",
    title: "Арматура А3 ⌀14 мм",
    brand: "ЕвразМеталл",
    category: "metal",
    subcategory: "Арматура",
    image: "/images/cat-metal.jpg",
    price: 520,
    unit: "м",
    inStock: 800,
    description:
      "Рифлёная арматура А-III, диаметр 14 мм. Для несущих конструкций.",
    specs: { Диаметр: "14 мм", Класс: "А-III (А400)" },
  },
  {
    slug: "ugolok-50x50",
    title: "Уголок 50×50×5",
    category: "metal",
    subcategory: "Уголок",
    image: "/images/cat-metal.jpg",
    price: 2200,
    unit: "м",
    inStock: 180,
    description: "Стальной равнополочный уголок 50×50×5 мм. Длина 6 м.",
    specs: { Размер: "50×50 мм", Толщина: "5 мм" },
  },

  // SUKHIE SMESI
  {
    slug: "cement-m500-50",
    title: "Цемент М500 Д0, 50 кг",
    brand: "Семейцемент",
    category: "smes",
    subcategory: "Цемент",
    image: "/images/cat-smes.jpg",
    price: 2750,
    oldPrice: 3100,
    unit: "мешок",
    inStock: 220,
    badge: "Акция",
    description:
      "Портландцемент М500 Д0 без добавок. Прочный, морозостойкий. Для бетона и кладочных растворов.",
    specs: { Марка: "М500 Д0", Вес: "50 кг", Срок: "60 дней" },
  },
  {
    slug: "knauf-rotband-30",
    title: "Штукатурка Knauf Rotband, 30 кг",
    brand: "KNAUF",
    category: "smes",
    subcategory: "Штукатурки",
    image: "/images/cat-smes.jpg",
    price: 3850,
    unit: "мешок",
    inStock: 140,
    badge: "Хит",
    description:
      "Гипсовая штукатурка Knauf Rotband для внутренних работ. Расход ~8,5 кг/м² при слое 10 мм.",
    specs: { Тип: "Гипсовая", Вес: "30 кг", Слой: "5–50 мм" },
  },
  {
    slug: "ceresit-cm11-25",
    title: "Клей плиточный Ceresit CM 11, 25 кг",
    brand: "CERESIT",
    category: "smes",
    subcategory: "Клей для плитки",
    image: "/images/cat-smes.jpg",
    price: 4250,
    unit: "мешок",
    inStock: 95,
    description:
      "Цементный клей для керамической плитки внутри и снаружи. Расход 3–4 кг/м².",
    specs: { Тип: "Цементный", Вес: "25 кг", Толщина: "2–6 мм" },
  },
  {
    slug: "knauf-fugen-25",
    title: "Шпаклёвка Knauf Fugen, 25 кг",
    brand: "KNAUF",
    category: "smes",
    subcategory: "Шпаклёвки",
    image: "/images/cat-smes.jpg",
    price: 3450,
    unit: "мешок",
    inStock: 70,
    description:
      "Гипсовая шпаклёвка для заделки швов гипсокартона и финишного выравнивания.",
    specs: { Тип: "Гипсовая", Вес: "25 кг" },
  },
  {
    slug: "alinex-pol-25",
    title: "Наливной пол ALINEX, 25 кг",
    brand: "ALINEX",
    category: "smes",
    subcategory: "Наливной пол",
    image: "/images/cat-smes.jpg",
    price: 2900,
    unit: "мешок",
    inStock: 110,
    description:
      "Самовыравнивающаяся смесь для финишного выравнивания пола. Слой 2–30 мм.",
    specs: { Слой: "2–30 мм", Вес: "25 кг" },
  },

  // PLITNYE
  {
    slug: "osb-3-12",
    title: "ОСБ-3 12 мм, 1250×2500",
    brand: "Kronospan",
    category: "wood",
    subcategory: "ОСБ",
    image: "/images/cat-wood.jpg",
    price: 6850,
    unit: "лист",
    inStock: 145,
    badge: "Хит",
    description:
      "Влагостойкая ориентированно-стружечная плита. Для черновых полов, обшивки каркасных стен, кровли.",
    specs: { Размер: "1250×2500 мм", Толщина: "12 мм", "Класс эмиссии": "E1" },
  },
  {
    slug: "fanera-fk-18",
    title: "Фанера ФК 18 мм, 1525×1525",
    category: "wood",
    subcategory: "Фанера",
    image: "/images/cat-wood.jpg",
    price: 9500,
    unit: "лист",
    inStock: 62,
    description: "Берёзовая фанера ФК для внутренних работ, мебели, опалубки.",
    specs: { Размер: "1525×1525 мм", Толщина: "18 мм", Сорт: "2/3" },
  },
  {
    slug: "gkl-knauf-12",
    title: "Гипсокартон Knauf 12,5 мм",
    brand: "KNAUF",
    category: "wood",
    subcategory: "Гипсокартон",
    image: "/images/cat-wood.jpg",
    price: 2950,
    unit: "лист",
    inStock: 320,
    description:
      "Стандартный гипсокартонный лист 1200×2500×12,5 мм. Для перегородок и потолков.",
    specs: { Размер: "1200×2500 мм", Толщина: "12,5 мм" },
  },
  {
    slug: "gkl-vlagostoiki",
    title: "Гипсокартон влагостойкий 12,5 мм",
    brand: "KNAUF",
    category: "wood",
    subcategory: "Гипсокартон",
    image: "/images/cat-wood.jpg",
    price: 3650,
    unit: "лист",
    inStock: 180,
    description: "Зелёный влагостойкий ГКЛ для ванных и кухонь.",
  },
  {
    slug: "dvp-3-2",
    title: "ДВП 3,2 мм, 1700×2745",
    category: "wood",
    subcategory: "ДВП",
    image: "/images/cat-wood.jpg",
    price: 1850,
    unit: "лист",
    inStock: 260,
    description:
      "Древесно-волокнистая плита для подложки и мебельных задних стенок.",
  },

  // PROFNASTIL
  {
    slug: "profnastil-c21",
    title: "Профнастил С-21 кровельный",
    category: "profnastil",
    subcategory: "Кровельный",
    image: "/images/cat-profnastil.jpg",
    price: 3450,
    unit: "м²",
    inStock: 720,
    badge: "Хит",
    description:
      "Кровельный профнастил С-21 с полимерным покрытием. Толщина 0,45 мм. Любой цвет под заказ за 3 дня.",
    specs: { Высота: "21 мм", Толщина: "0,45 мм", Покрытие: "Полиэстер" },
  },
  {
    slug: "profnastil-c8",
    title: "Профнастил С-8 стеновой",
    category: "profnastil",
    subcategory: "Стеновой",
    image: "/images/cat-profnastil.jpg",
    price: 2950,
    unit: "м²",
    inStock: 540,
    description: "Стеновой профнастил С-8 для забора и облицовки фасадов.",
    specs: { Высота: "8 мм", Толщина: "0,4 мм" },
  },
  {
    slug: "profnastil-h75",
    title: "Профнастил Н-75 несущий",
    category: "profnastil",
    subcategory: "Несущий",
    image: "/images/cat-profnastil.jpg",
    price: 5200,
    unit: "м²",
    inStock: 280,
    description: "Несущий профнастил для перекрытий и кровли больших пролётов.",
    specs: { Высота: "75 мм", Толщина: "0,7 мм" },
  },

  // DOORS
  {
    slug: "dver-mdf-mezh",
    title: "Дверь межкомнатная МДФ «Лотос»",
    category: "doors",
    subcategory: "Межкомнатные",
    image: "/images/cat-doors.jpg",
    price: 18500,
    unit: "шт",
    inStock: 22,
    description:
      "Межкомнатная дверь МДФ с ПВХ-покрытием. Полотно 800×2000 мм. Цвет: дуб, орех, венге.",
    specs: { Размер: "800×2000 мм", Материал: "МДФ + ПВХ" },
  },
  {
    slug: "dver-metall-vh",
    title: "Дверь входная металлическая",
    category: "doors",
    subcategory: "Входные",
    image: "/images/cat-doors.jpg",
    price: 72000,
    unit: "шт",
    inStock: 8,
    badge: "Новинка",
    description:
      "Входная стальная дверь с порошковой покраской. 2 контура уплотнителя, 3 ригеля.",
    specs: { Размер: "860×2050 мм", Толщина: "70 мм" },
  },
  {
    slug: "dver-bani-sosna",
    title: "Дверь для бани из массива сосны",
    category: "doors",
    subcategory: "Для бани",
    image: "/images/cat-doors.jpg",
    price: 24500,
    oldPrice: 28800,
    unit: "шт",
    inStock: 14,
    badge: "Акция",
    description:
      "Цельный массив сосны, без сучков. Размер 700×1800 мм. Готова к установке.",
  },

  // FLOOR
  {
    slug: "laminat-32",
    title: "Ламинат 32 класс «Дуб северный»",
    category: "floor",
    subcategory: "Ламинат",
    image: "/images/cat-floor.jpg",
    price: 2750,
    unit: "м²",
    inStock: 420,
    badge: "Хит",
    description:
      "Ламинат 32 класса, толщина 8 мм. Замок Click. Подходит для жилых и офисных помещений.",
    specs: { Класс: "32 (АС4)", Толщина: "8 мм" },
  },
  {
    slug: "laminat-33",
    title: "Ламинат 33 класс «Венге»",
    category: "floor",
    subcategory: "Ламинат",
    image: "/images/cat-floor.jpg",
    price: 3950,
    unit: "м²",
    inStock: 180,
    description: "Коммерческий ламинат 33 класса, фаска 4V, толщина 10 мм.",
    specs: { Класс: "33 (АС5)", Толщина: "10 мм" },
  },
  {
    slug: "linoleum-pk",
    title: "Линолеум полукоммерческий, 3 м",
    category: "floor",
    subcategory: "Линолеум",
    image: "/images/cat-floor.jpg",
    price: 1850,
    unit: "м²",
    inStock: 240,
    description:
      "Полукоммерческий линолеум, ширина рулона 3 м. Износостойкий, для прихожей и кухни.",
  },
  {
    slug: "vagonka-shtil",
    title: "Вагонка штиль, сосна, сорт А",
    category: "floor",
    subcategory: "Вагонка",
    image: "/images/cat-floor.jpg",
    price: 980,
    unit: "м²",
    inStock: 360,
    description:
      "Вагонка сорт А из сосны для обшивки стен и потолков. Длина 3 м.",
    specs: { Длина: "3 м", Сорт: "А", Толщина: "16 мм" },
  },
  {
    slug: "plintus-mdf",
    title: "Плинтус МДФ белый, 80 мм",
    category: "floor",
    subcategory: "Плинтус",
    image: "/images/cat-floor.jpg",
    price: 720,
    unit: "м",
    inStock: 1500,
    description: "Белый плинтус из МДФ с ламинацией. Длина хлыста 2,4 м.",
  },
];

export const BRANDS = [
  "KNAUF",
  "CERESIT",
  "TYTAN",
  "ALINEX",
  "ALIT",
  "ИЗОСПАН",
  "TECHNONICOL",
  "URSA",
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(catId: string) {
  return PRODUCTS.filter((p) => p.category === catId);
}

export function formatTenge(n: number): string {
  return new Intl.NumberFormat("ru-RU").format(Math.round(n)) + " ₸";
}
